import type { Metadata } from "next";
import Head from "next/head";
import "../globals.css";

export const metadata: Metadata = {
  title: "VolunteerQuest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/logo/favicon.png" />
      </Head>
      <body className="bg-background text-foreground font-sans">
        {children}
      </body>
    </html>
  );
}
